language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - py.test
before_install:
  - openssl aes-256-cbc -K $encrypted_c39c778b22cd_key -iv $encrypted_c39c778b22cd_iv
    -in .travis/deploy.key.enc -out .travis/deploy.key -d

after_success:
   - eval "$(ssh-agent -s)"
   - chmod 600 .travis/deploy.key
   - ssh-add .travis/deploy.key
   - ssh-keyscan soffun.alexv.se >> ~/.ssh/known_hosts
   - git remote add deploy dokku@soffun.alexv.se:ci
   - git config --global push.default simple
   - git push deploy master
