language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - py.test
before_install:
  - openssl aes-256-cbc -K $encrypted_c39c778b22cd_key -iv $encrypted_c39c778b22cd_iv
    -in .travis/deploy.key.enc -out .travis/deploy.key -d

